openapi: 3.0.0

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
    - name: User
      description: All related to users.
      color: "ffffff"
